export const ENDPOINT: String = "http://localhost:8000/api";

const INVITATION_STATUS = {
  UNKNOWN: "UNKNOWN",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  READY_FOR_CHECKIN: "READY_FOR_CHECKIN",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  CHECKED_IN: "CHECKED_IN",
  CHECKED_OUT: "CHECKED_OUT",
  PENDING_REVIEW: "PENDING_REVIEW",
} as const;

export { INVITATION_STATUS };
