export const ENDPOINT: String = "http://localhost:8000/api";

export const WEBSOCKET_ENDPOINT: string =
  "ws://localhost:8000/ws/realtime_invitations";

const INVITATION_STATUS = {
  UNKNOWN: "UNKNOWN",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  READY_FOR_CHECKIN: "READY_FOR_CHECKIN",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  CHECKED_IN: "CHECKED_IN",
  CHECKED_OUT: "CHECKED_OUT",
  PENDING_REVIEW: "PENDING_REVIEW",
} as const;

export const INVITES_NAME = "INVITES";
export const REQUEST_NAME = "REQUESTS";

export { INVITATION_STATUS };
